import Footer from "@/components/Shared/Footer";
import Navbar from "@/components/Shared/Navbar";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainLayout({ children }) {
    return (
        <>
            <Navbar></Navbar>

            {children}

            <Footer></Footer>
        </>
    );
}
