import SideBar from "@/components/Shared/SideBar";

export const metadata = {
  title: "Next JS DashBoard",
  description: "Generated by create next app",
};
const DashBoardlayout = ({children}) => {
  return (
    <div>
      <header className="text-center text-white bg-black"><h2>This is Header for Dashboard</h2></header>
      <div className="inline-flex">
      <SideBar></SideBar>
      <div className="w-full">
        {children}
      </div>
      </div>
      <footer className="text-center text-white bg-black"><h2>This is Footer for Dashboard</h2></footer>

    </div>
  );
};

export default DashBoardlayout;